<?php

use App\Http\Controllers\ContactUs;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\MainController;
use App\Http\Controllers\AdminController;
use App\Http\Controllers\EventController;
use App\Http\Controllers\LoginController;
use App\Http\Controllers\MovieController;
use App\Http\Controllers\SportController; 
use App\Http\Middleware\CheckAvailability;
use App\Http\Controllers\BookingController;
use App\Http\Controllers\ResetPasswordController;
use App\Http\Controllers\ForgotPasswordController;


Route::get('/', [MainController::class, 'Home']);
Route::get('/home', [MainController::class, 'Home'])->name('home');
Route::get('/movies', [MovieController::class, 'movies'])->name('movies');
Route::get('/movies/filter', [MovieController::class, 'filterMovies'])->name('movies.filter');
Route::get('/movies/search', [MovieController::class, 'search'])->name('movies.search');
Route::get('/events/search', [EventController::class, 'search'])->name('events.search');
Route::get('/sports/search', [SportController::class, 'search'])->name('sports.search');
Route::get('/movies/genre/{id}', [MovieController::class, 'filterByGenre'])->name('movies.filterByGenre');
Route::get('/events', [EventController::class, 'events'])-> name ('events');
Route::get('/filter-events', [EventController::class, 'filterEvents'])->name('filter.events');
Route::get('/sports', [SportController::class, 'sports'])-> name ('sports');
Route::get('/filter-sports', [SportController::class, 'filterSports'])->name('filter.sports');
Route::get('/login',[MainController::class, 'login'])->name('login');
Route::get('/signup',[MainController::class, 'signup'])->name('signup');
Route::get('/events/type/{id}', [EventController::class, 'Eventsfilter'])->name('eventsfilter');
Route::get('/sports/type/{id}', [SportController::class, 'Sportsfilter'])->name('sportsfilter');
Route::get('/movies/{id}', [MovieController::class, 'show'])->name('movie_detail');
Route::post('/signup', [AuthController::class, 'signup'])->name('signup');
Route::post('/logout', [AuthController::class, 'logout'])->name('logout');
Route::post('/login', [LoginController::class, 'login'])->name('login');
Route::get('/movies/moviesbooking/{id}', [MovieController::class, 'moviesbookig']) -> name('moviesbooking') -> middleware(['auth', CheckAvailability::class . ':Movie']);
Route::get('/events/eventsbooking/{id}', [EventController::class, 'eventsbooking']) -> name('eventsbooking') ->  middleware(['auth', CheckAvailability::class . ':Event']);;
Route::get('/sports/sportsbooking/{id}', [SportController::class, 'sportsbooking']) -> name('sportsbooking') ->  middleware(['auth', CheckAvailability::class . ':Sport']);;
Route::post('/booking/bookingmovies', [BookingController::class, 'bookingmovies'])->name('bookingmovies');
Route::post('/booking/bookingevents', [BookingController::class, 'bookingevents'])->name('bookingevents');
Route::post('/booking/bookingsports', [BookingController::class, 'bookingsports'])->name('bookingsports');
Route::get('/admin', [AdminController::class, 'index'])->name('admin.page');
Route::get('/admin/movies', [AdminController::class, 'movies'])->name('admin.movies');
Route::get('/admin/events', [AdminController::class, 'events'])->name('admin.events');
Route::get('/admin/sports', [AdminController::class, 'sports'])->name('admin.sports');
Route::get('/admin/users', [AdminController::class, 'users'])->name('admin.users');
Route::get('/admin/movies/filter', [MovieController::class, 'adminmoviesfilter'])->name('adminmovies.filter');
Route::get('/admin/events/filter', [EventController::class, 'adminfilterEvents'])->name('adminevents.filter');
Route::get('/search', [EventController::class, 'adminsearch'])->name('adminevents.search');
Route::get('/addmovies', [AdminController::class, 'addmovies'])->name('addmovies');
Route::post('/movies/store', [MovieController::class, 'store'])->name('movies.store');
Route::delete('/admin/events/{id}/delete', [EventController::class, 'deleteEvent'])->name('admin.events.delete');
Route::delete('/admin/movies/{id}', [MovieController::class, 'destroy'])->name('admin.movies.destroy');
Route::delete('/events/{id}', [EventController::class, 'destroy'])->name('events.destroy');
Route::POST('/movies/{id}', [MovieController::class, 'update'])->name('movies.update');
Route::POST('/events/{id}', [EventController::class, 'update'])->name('events.update');
Route::POST('/sports/{id}', [SportController::class, 'update'])->name('sports.update');
Route::get('/editmovies/{id}', [AdminController::class, 'edit'])->name('editmovies');
Route::get('/editsports/{id}', [AdminController::class, 'sportedit'])->name('sportedit');
Route::get('/editmevents/{id}', [AdminController::class, 'Eventedit'])->name('Eventedit');
Route::get('/admin/users/filter-users', [AdminController::class, 'filterUsers'])->name('filter.users');
Route::get('/mybookings', [BookingController::class, 'myBookings'])->name('mybookings');
Route::post('/events/store', [EventController::class, 'store'])->name('events.store');
Route::post('/sports/store', [SportController::class, 'store'])->name('sports.store');
Route::get('/admin/events/add', [EventController::class, 'create']) -> name('events.create');
Route::get('/admin/sports/add', [SportController::class, 'create']) -> name('sports.create');
Route::get('/admin/sports/filter', [SportController::class, 'filter'])->name('adminsports.filter');
Route::delete('/admin/sports/{id}/delete', [SportController::class, 'destroy'])->name('admin.sports.destroy');
Route::delete('/user/{id}/delete', [AuthController::class, 'destroy'])->name('user.destroy');
Route::get('/contactus', [ContactUs::class, 'view'])->name('contactus');
Route::post('/contactus', [ContactUs::class, 'sendEmail'])->name('contact.send');
Route::get('forgot-password', [ForgotPasswordController::class, 'showLinkRequestForm'])->name('password.request');
Route::post('forgot-password', [ForgotPasswordController::class, 'sendResetLinkEmail'])->name('password.email');
Route::get('reset-password/{token}', [ResetPasswordController::class, 'showResetForm'])->name('password.reset');
Route::post('reset-password', [ResetPasswordController::class, 'reset'])->name('password.update');